---
- name: Verificando NTP
  yum: pkg=ntp.x86_64 state=latest
  tags: all-ntp

- name: Configurando NTP - CentOS 7
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  notify: 
    - Habilitando NTP - CentOS 7
    - Iniciando NTP - CentOS 7
  tags: all-ntp

- name: Configurando NTP - CentOS 6
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  notify: 
    - Habilitando NTP - CentOS 6
    - Iniciando NTP - CentOS 6
  tags: all-ntp

- name: Configurando NTP - CloudLinux
  template: src=etc/ntp.conf.j2 dest=/etc/ntp.conf
  when: (ansible_distribution == "CloudLinux" and ansible_distribution_major_version == "7")
  notify: 
    - Habilitando NTP - CentOS 7
    - Iniciando NTP - CentOS 7
  tags: all-ntp