---
- name: MOTD - Criando (1/4)
  copy: src=usr/local/bin/systemstats.sh dest=/usr/local/bin/systemstats.sh mode=0755
  tags: all-motd
  
- name: MOTD - Instalando dependencias (2/4)
  yum: pkg=bc.x86_64 state=latest
  tags: all-motd
  
- name: MOTD - Executando Manualmente (3/4)
  shell: /usr/local/bin/systemstats.sh
  args:
    executable: /bin/bash
  tags: all-motd
  
- name: MOTD - Cadastrando crontab (4/4)
  lineinfile:
    dest: /etc/crontab
    line: "*/5 * * * * root /usr/local/bin/systemstats.sh"
  tags: all-motd
