---
###### CentOS 7 #####
- name: Habilitando NTP - CentOS 7
  service: name=ntpd.service enabled=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Iniciando NTP - CentOS 7
  service: name=ntpd.service state=restarted
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

##### CentOS 6 ##### 
- name: Habilitando NTP - CentOS 6
  service: name=ntpd enabled=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: Iniciando NTP - CentOS 6
  service: name=ntpd state=restarted
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

##### CloudLinux ##### 
- name: Habilitando NTP - CloudLinux
  service: name=ntpd.service enabled=yes
  when: (ansible_distribution == "CloudLinux" and ansible_distribution_major_version == "7")

- name: Iniciando NTP - CloudLinux
  service: name=ntpd.service state=restarted
  when: (ansible_distribution == "CloudLinux" and ansible_distribution_major_version == "7")